import { CategoryModel } from "./models/category.model";
import { ProductGender, ProductModel } from "./models/product.model";

export const productCategories: CategoryModel[] = [
  { id: 1, name: "T-shirts" },
  { id: 2, name: "Chemises" },
  { id: 3, name: "Pulls" },
  { id: 4, name: "Sweat-shirts" },
  { id: 5, name: "Vestes" },
  { id: 6, name: "Manteaux" },
  { id: 7, name: "Pantalons" },
  { id: 8, name: "Jeans" },
  { id: 9, name: "Shorts" },
  { id: 10, name: "Jupes" },
  { id: 11, name: "Robes" },
  { id: 12, name: "Costumes" },
  { id: 13, name: "Survêtements" },
  { id: 14, name: "Maillots de bain" },
  { id: 15, name: "Lingerie" },
  { id: 16, name: "Soutiens-gorge" },
  { id: 17, name: "Culottes" },
  { id: 18, name: "Pyjamas" },
  { id: 19, name: "Chaussettes" },
  { id: 20, name: "Collants" },
  { id: 21, name: "Blazers" },
  { id: 22, name: "Chemisiers" },
  { id: 23, name: "Pantalons de costume" },
  { id: 24, name: "Blouses" },
  { id: 25, name: "Tops" },
  { id: 26, name: "Combinaisons" },
  { id: 27, name: "Vêtements de nuit" },
  { id: 28, name: "Tuniques" },
  { id: 29, name: "Cardigans" }
];

export const products: ProductModel[] = [
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Homme,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"aroduit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Femme,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"broduit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"croduit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  },
  {
    id:1,
    name:"Produit de Sport 1",
    description:"Description du produit de sport 1",
    quantity:31,
    availability:false,
    price:127,
    gender: ProductGender.Unisexe,
    imageSlug:"xeXOh.jpg",
    categoryId:1,
    subCategoryId:1
  }
]